server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Fichiers statiques
  location / {
    try_files $uri /index.html;
  }

  # Cache basique pour assets fingerprintés (si CRA/Vite génère des hashes)
  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
    expires 7d;
    access_log off;
    try_files $uri =404;
  }

  # Santé simple
  location = /healthz {
    return 200 "ok";
    add_header Content-Type text/plain;
  }
}