image:
  repository: docker.io/jaffleman971/maptdp-frontend
  tag: "sha-c545994"

ingress:
  enabled: true
  host: "maptdp.dev.jaffleman.tech"

runtimeConfig:
  apiBaseUrl: "https://api.dev.jaffleman.tech/"

replicaCount: 1