{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "maptdp.fullname" . }}-ingress
  labels:
    {{- include "maptdp.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.host }}
      secretName: {{ include "maptdp.fullname" . }}-tls
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "maptdp.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}

          {{- if .Values.frontend.ingress.api.enabled }}
          - path: {{ .Values.frontend.ingress.api.path | default "/api" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "maptdp.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}