frontend:
  image:
    tag: "v2.0.0"
  ingress:
    host: "tdp.jaffleman.tech"
  runtimeConfig:
    apiBaseUrl: "https://api.jaffleman.tech"

backend:
  replicaCount: 2
  image:
    tag: "v2.0.0"
  ingress:
    host: "api.jaffleman.tech"
    path: /
  env:
    - name: NODE_ENV
      value: "production"
    - name: LOG_LEVEL
      value: "info"

#    - name: DATABASE_URL
#      valueFrom:
#        secretKeyRef:
#          name: maptdp-db
#          key: url