frontend:
  image:
    tag: "v0.1.0"
  ingress:
    host: "maptdp.jaffleman.tech"
  runtimeConfig:
    apiBaseUrl: "https://api.jaffleman.tech"

backend:
  image:
    tag: "v0.1.0"
  ingress:
    host: "api.jaffleman.tech"
    path: /
  env:
    - name: LOG_LEVEL
      value: "info"
#    - name: DATABASE_URL
#      valueFrom:
#        secretKeyRef:
#          name: maptdp-db
#          key: url