frontend:
  image:
    repository: docker.io/jaffleman971/maptdp-frontend
    tag: "v1.1.3"
  ingress:
    host: "maptdp.dev.jaffleman.tech"
  runtimeConfig:
    apiBaseUrl: "https://api.dev.jaffleman.tech"
backend:
  replicaCount: 1
  image:
    repository: docker.io/jaffleman971/maptdp-backend
    tag: "v1.1.3"
  ingress:
    host: "api.dev.jaffleman.tech"
  env:
  - name: LOG_LEVEL
    value: "debug"
