apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: maptdp
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "frontend"
      images:
        - alias: frontend
          imageName: docker.io/jaffleman971/maptdp-frontend
          commonUpdateSettings:
            updateStrategy: latest
            allowTags: "regexp:^sha-[0-9a-f]+$"
            forceUpdate: true
          manifestTargets:
            helm:
              name: "frontend.image.repository"
              tag:  "frontend.image.tag"

    - namePattern: "backend"
      images:
        - alias: backend
          imageName: docker.io/jaffleman971/maptdp-backend
          commonUpdateSettings:
            updateStrategy: latest
            allowTags: "regexp:^sha-[0-9a-f]+$"
            forceUpdate: true
          manifestTargets:
            helm:
              name: "backend.image.repository"
              tag:  "backend.image.tag"

  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: "helmvalues:values-dev.yaml"