apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: maptdp-db
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "maptdp-db"   # <-- remplace par le nom exact de l'Application DB
      images:
        - alias: db
          imageName: docker.io/jaffleman971/maptdp-db:~16
          commonUpdateSettings:
            updateStrategy: semver
            forceUpdate: true     # tu pourras l’enlever après le premier passage
          manifestTargets:
            helm:
              name: "db.image.repository"   # adapte si tes clés Helm diffèrent
              tag:  "db.image.tag"

  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: "helmvalues:values.yaml"  # chemin relatif au chart DB