apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maptdp-db
  namespace: argocd
  metadata:
    annotations:
      argocd-image-updater.argoproj.io/image-list: db=docker.io/jaffleman971/maptdp-db
      argocd-image-updater.argoproj.io/db.update-strategy: semver
      argocd-image-updater.argoproj.io/db.allow-tags: regexp:^([0-9]+\.[0-9]+)$
      argocd-image-updater.argoproj.io/write-back-method: helm



spec:
  project: default
  source:
    repoURL: https://github.com/jaffleman/New_MapTdp.git
    targetRevision: main
    path: deploy/charts/maptdp-db
  destination:
    server: https://kubernetes.default.svc
    namespace: maptdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true