apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-approle-token
  namespace: maptdp
spec:
  encryptedData:
    secret-id: AgAemWEyRiFW7fWaVYpTnAw7Afm1x0SEHul8+VQjPVsy/EX2jo9D1JSshxekEQhwfHEjtFuqJGK7J2mJHBfCt+rM/VLIWxjf9NE0N+T6e5wo5l87EaQSKvYsF/9odmRaIro+LVKL0ze9/+5JoOLc3xNl5XLxkHkgkRdhZ5DG+2sXJSxM3MrGUtw5UxBTyM8Dct7PUoLK/W3dtWzYZk6/WK3lB+iF6uIun6y6r5tVa60Pkce6FA/DKIqhXmuTtAV9lu9X/7XT95ehveKtQuvVoATDgsvcw+JAlRQAxOE9I7ZfG3o+C/EC5GP6nB1xJldiowIL11sSxPKS0+rBvuyZUVamfbtysEEWkkjjCClscpb7zSw2+VR5WoQDIS2UUbTmE4DyB3ZJoUk0GRkkAxMmc3sWEqaWwLhMgGVyIVxw3sfHAmWBvXErFLJa3yJlrDZQRjyddXzXxWWrTqvIMVrrxxiLxBcfH3J5G8clwvasxUbBa0tR3oJqOEGqng27chDLTP24fEm+ow2yqq8ahQA/ECdlitnlD8fuUsojMKPBho7MtzGb5j+fa3zvUHjVf7GJYYsCdGu9Gg1WREsacKbu+SD7DyUtIFUvnHFpCZHuZ85KJApyZ1+jHZCAjfpy0XC1TitM7zCaC+iOJNiFU2YDtp5VHN5YQmxj65uttkQq6IMJyfOOpYPl124gPH+DSY+MFHbJywiBGVO/v+ho9gBib0gWqAPYfRijaVctqco/gDe+QsEQWX4=
  template:
    metadata:
      creationTimestamp: null
      name: vault-approle-token
      namespace: maptdp
