apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: maptdp
spec:
  provider:
    vault:
      server: "https://vault.jaffleman.tech"
      path: "k3s"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "maptdp-role"