apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.20

    helm:
      parameters:
        - name: installCRDs
          value: "false"   
        - name: webhook.enabled
          value: "true"
        - name: certController.enabled
          value: "true"
        - name: serviceMonitor.enabled
          value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
